# Generated by Django 2.2.7 on 2019-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Islamabad,Pakistan', max_length=35),
        ),
    ]
