# Generated by Django 2.2.7 on 2019-12-15 12:58

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='200', help_text='Enter the amount in US Dollars $', max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='username@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=phone_field.models.PhoneField(default='+923186482764', help_text='Contact Phone Number', max_length=31),
        ),
    ]
