# Generated by Django 2.2.7 on 2019-12-15 13:28

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191215_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=phone_field.models.PhoneField(default='+923186482764', help_text='+[country code][number]x[extension]', max_length=31),
        ),
    ]
