# Generated by Django 2.2.7 on 2019-12-17 12:36

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191215_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the amount in US Dollars $', max_digits=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=phone_field.models.PhoneField(help_text='+[country code][number]x[extension]', max_length=31),
        ),
    ]
