# Generated by Django 2.2.7 on 2019-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191217_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='brief',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Please Mention your Jazzcash or EasyPaisa account (If Any)'),
        ),
    ]
