# Generated by Django 2.2.7 on 2019-12-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191219_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brief',
            field=models.TextField(help_text='Write an overview to be displayed on Homepage', max_length=350),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(help_text='Enter the email so that someone can contact you in case of any help ', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(help_text='Kindly atleast mention City,Country', max_length=35),
        ),
    ]
