# Generated by Django 2.2.7 on 2019-12-19 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20191219_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bankaccount',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cnic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11111111111111111111111111)]),
        ),
        migrations.AddField(
            model_name='post',
            name='mobileAccount',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
