# Generated by Django 2.2.7 on 2019-12-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20191219_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bankaccount',
            new_name='bankAccount',
        ),
    ]
