# Generated by Django 2.2.7 on 2019-12-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20191219_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mobileAccount',
            field=models.CharField(blank=True, help_text='Enter your Jazzcash or EasyPaisa Account</br>This is for Jazzcash or EasyPaisa money transfer', max_length=15, null=True),
        ),
    ]
