# Generated by Django 2.2.7 on 2019-12-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20191219_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cnic',
            new_name='cNIC',
        ),
    ]
