# Generated by Django 2.2.7 on 2019-12-19 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20191219_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cNIC',
            field=models.IntegerField(blank=True, help_text='This is for Jazzcash / EasyPaisa money transfer', null=True, validators=[django.core.validators.MaxValueValidator(26)]),
        ),
    ]
