# Generated by Django 2.2.7 on 2019-12-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20191219_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cNIC',
            field=models.CharField(blank=True, help_text='This is for Jazzcash / EasyPaisa money transfer', max_length=13, null=True),
        ),
    ]
