# Generated by Django 2.2.7 on 2019-12-19 15:33

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20191219_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='+[country code][number]x[extension]', max_length=31, null=True),
        ),
    ]
