# Generated by Django 2.2.7 on 2019-12-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20191219_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brief',
            field=models.TextField(help_text='Write an overview to be displayed on Homepage', max_length=500),
        ),
    ]
